on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'  # Set the version you prefer, e.g., '14' or '16'

      - name: Install Dependencies
        run: npm install

      - name: Deploy to AWS EC2
        uses: easingthemes/ssh-deploy@v2
        with:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          REMOTE_PORT: 22
          SOURCE: "."  # Path to your Node.js app
          TARGET: "/home" 
          
