name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js and npm
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install application dependencies
        run: npm install

      - name: SSH into EC2 instance and deploy
        uses: appleboy/ssh-action@master
        with:
        
          host: 3.210.178.208
          
