name: Node.js Application Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install Dependencies
        run: npm install

      - name: Deploy to AWS EC2
        uses: easingthemes/ssh-deploy@v2
        with:
          server: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          port: 22
          local_path: '.'  # Path to your Node.js app
          remote_path: '/path/to/remote/directory'  # Remote path on EC2

      - name: Restart Node.js App
        run: |
          ssh -i ${{ secrets.EC2_PRIVATE_KEY }} ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} 'cd /path/to/remote/directory && npm install && pm2 restart your-app'
