name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install

      - name: Deploy to EC2
        uses: appleboy/scp-action@master
        with:
          host: 3.210.178.208
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          port: 22
          source: "."  # Path to your Node.js app
          target: "/path/to/remote/directory"  # Remote path on EC2
